### ISSUE TITLE
Scale bar in the comparison tree is different from my input tree

### ISSUE THREAD

**Issue by maycol1551** [jolobito/SPdel#48]
I have been using this code to compare a COI-5P dataset:
SPdel.py My_COI-5P.fasta  -P -T -t My_RAxML_tree.nwk -X External_comparison.csv -C ASAP,ABGD,PTP,bPTP,GMYC

The csv file contains the results from the ABGD,ASAP and GMYC. My external tree is a RAxML tree. 

I got the final comparison tree with the 5 species delimitation methods and the consensus. Everything looks correct except for the scale bar in the comparison tree. The scale bar values are different from the input RAxML tree. 

Also, is there a way to keep the bootstrap values in the comparison tree? 

I am using a linux system.

Thank you

**Comment by jolobito** [comment]
Hi @maycol1551. We are working in a new version incluiding the support values in the tree. 
Certainly the scale bar length seem to be a issue! Thanks for reporting! We will check that

**Comment by jolobito** [comment]
The scalebar issue was solved. Please reinstall the SPdel to test! Thanks!

**Comment by maycol1551** [comment]
Hi @jolobito I confirm the scale bar issue has been fixed. Everything looks good now. This tools is awesome, I am looking forward for the next version that includes the bootstraps values.
